/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HomepagePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  homepagePath: "Homepage.md"
};
function isMarkdownView(leaf) {
  return leaf.view?.getViewType() === "markdown";
}
var HomepagePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.layoutReady = false;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "open-homepage",
      name: "\u6253\u5F00\u9996\u9875",
      callback: () => this.openHomepage()
    });
    this.app.workspace.onLayoutReady(() => {
      this.layoutReady = true;
      const openLeaves = this.app.workspace.getLeavesOfType("markdown").filter(isMarkdownView);
      if (openLeaves.length === 0) {
        this.openHomepage();
      }
    });
    this.addSettingTab(new HomepageSettingTab(this.app, this));
  }
  onunload() {
  }
  async openHomepage() {
    const path = this.settings.homepagePath;
    let file = this.app.vault.getAbstractFileByPath(path);
    if (!file) {
      file = await this.app.vault.create(
        path,
        "# \u6B22\u8FCE\u4F7F\u7528 Obsidian\n\n\u8FD9\u662F\u4F60\u7684\u9996\u9875\u3002\u70B9\u51FB\u5DE6\u4FA7\u7F16\u8F91\u6309\u94AE\uFF0C\u81EA\u7531\u4FEE\u6539\u8FD9\u91CC\u7684\u5185\u5BB9\u3002\n\n\u4F60\u53EF\u4EE5\u6DFB\u52A0\u4EFB\u52A1\u5217\u8868\u3001\u7B14\u8BB0\u94FE\u63A5\u3001\u56FE\u7247\u3001\u6216\u5176\u4ED6\u4EFB\u4F55 Markdown \u5185\u5BB9\u3002\n\n---\n\n> \u7528 `Cmd/Ctrl + Shift + H` \u968F\u65F6\u56DE\u5230\u8FD9\u91CC\u3002"
      );
    }
    if (file instanceof import_obsidian.TFile) {
      await this.app.workspace.openLinkText(file.path, "", false);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var HomepageSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Homepage \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u9996\u9875\u6587\u4EF6\u8DEF\u5F84").setDesc("\u76F8\u5BF9\u4E8E vault \u6839\u76EE\u5F55\u7684 Markdown \u6587\u4EF6\u8DEF\u5F84\uFF0C\u4F8B\u5982 Homepage.md \u6216 folder/Welcome.md").addText(
      (text) => text.setPlaceholder("Homepage.md").setValue(this.plugin.settings.homepagePath).onChange(async (value) => {
        this.plugin.settings.homepagePath = value.trim() || "Homepage.md";
        await this.plugin.saveSettings();
      })
    );
  }
};
